///Hive types
const int HIVE_TYPE_ID_BUY_VO = 1;
const int HIVE_TYPE_ID_BOOK_VO = 2;
const int HIVE_TYPE_ID_BOOK_LIST_VO = 3;
const int HIVE_TYPE_ID_BOOK_LIST_RESULTS_VO = 4;
const int HIVE_TYPE_ID_BOOK_REVIEW_VO = 5;
const int HIVE_TYPE_ID_BOOK_DETAILS_VO = 6;
const int HIVE_TYPE_ID_BOOK_IS_BN_VO = 7;
const int HIVE_TYPE_ID_BOOK_DETAILS_LIST_VO = 8;
const int HIVE_TYPE_ID_BUY_LINKS_VO = 9;
const int HIVE_TYPE_ID_SEARCH_BOOK_VO = 10;
const int HIVE_TYPE_SHELF_VO = 11;

///Box Name
const String BOX_NAME_CHANGE_STYLE = "BOX_NAME_CHANGE_STYLE";
const String BOX_NAME_SORT_TYPE = "BOX_NAME_SORT_TYPE";
const String BOX_NAME_BOOK_LIST = "BOX_NAME_BOOK_LIST";
const String BOX_NAME_BOOK_DETAILS_LIST = "BOX_NAME_BOOK_DETAILS_LIST";
const String BOX_NAME_STORAGE_BOOK_LIST = "BOX_NAME_STORAGE_BOOK_LIST";
const String BOX_NAME_STORAGE_SHELF_LIST = "BOX_NAME_STORAGE_SHELF_LIST";